# Generated by Django 4.2.16 on 2025-05-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
